### ISSUE TITLE
Magento 2.2.2 gk route does not work

### ISSUE THREAD

**Issue by flavioamello** [guardiankey/guardiankey-magento2-authsecurity#1]
On magento 2.2.2 there is a validation where route's id must have at least 3 characters.
Changing route id to "gkey" for example on /etc/frontend/routes.xml make it work properly.

```xml
<?xml version="1.0" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:App/etc/routes.xsd">
    <router id="standard">
        <route frontName="gk" id="gkey">
            <module name="GuardianKey_AuthSecurity"/>
        </route>
    </router>
</config>
```

**Comment by pauloangelo** [comment]
@flavioamello ,

Thank you! Your suggestion is implemented in commit cda247094f76aeef080400c8b895f099125e5b01 .

regards ;)
